apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
stringData:
  DB_PASS: "postgres"
  DATABASE_URL: "postgresql://postgres:postgres@db-service.database.svc.cluster.local:5432/app"
