apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  DB_USER: ${DB_USER}
  DB_HOST: "db-service.database.svc.cluster.local"
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  BACKEND_PORT: "3000"
