apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  DB_USER: "postgres"
  DB_HOST: "db-service.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "app"
  BACKEND_PORT: "3000"
