apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: database
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: ${DB_PORT}
    protocol: TCP
    name: postgres
