name: Build and Push Service Images

on:
  push:
    branches:
      - main
      - feature/createWorkflows

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }} 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. BUILD & PUSH DO BACKEND
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-event-hub:${{ github.sha }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 2. BUILD & PUSH DO FRONTEND
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-event-hub:${{ github.sha }} 
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }} # Usa a variÃ¡vel definida no bloco 'env'

  notify_failure:
    runs-on: ubuntu-latest
    needs: build 
    if: failure()

    steps:
      - name: Set error message variables
        id: error_info
        run: |
          echo "error_message=A pipeline falhou no branch ${{ github.ref_name }}." >> $GITHUB_OUTPUT
          echo "job_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Discord Notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: FF0000
          username: "CI/CD Bot"
          message: |
            ðŸ”´ Falha na Pipeline CI/CD ðŸ”´
            Status do Job: ${{ needs.build.result }}
            Mensagem: ${{ steps.error_info.outputs.error_message }}
            Detalhes: [Ver logs completos aqui](${{ steps.error_info.outputs.job_url }})